### ISSUE TITLE
Moon Rise Towers - Act 2

### ISSUE THREAD

**Issue by 122abc123** [plasticmacaroni/bg3-missables#4]
Things people may miss

- During Assault with Harpers and Flaming fist, even if you cleared the tower there is a big fight in the dungeons (that grants a inspiration, and a nice chunk of exp, was my level 10 just before Kethric fight having done everything else, so assume same for most trying to 100% it all), imagine lots of people would miss this, especially if they had already cleared the dungeon prior to the fight

- In Balthazar's Secret Lab, the sigil to create a shadow lantern that summons shadows

- Three winged horrors you can fight, if you climb the exterior of the tower, that I assume most people miss (they say they are hungry, perhaps you can get them to attack moonrise forces, but I only  remember being able to convince them to leave or fight, but did not explore all options)

- Talking to the cat on exterior of the tower hunting a dead tadpole, and cat in the inn, there is only an inspiration point and fun dialog, if you manage to speak to both "Lord and hunter" (for Urchin only), so may not be worth including

- mimic in his daughters room

**Comment by plasticmacaroni** [comment]
Added in https://github.com/plasticmacaroni/bg3-missables/commit/3c9f433d97e73d95f3f29a741bb8ed295df0f2f4

I decided not to include the winged horrors, because I couldn't find a way to make them attack the Moonrise forces. That was really cool, though!

The shadow lantern summon was a really great addition! 

I also didn't include talking to the cat, as I couldn't find any permanent effects. 

The mimic does drop an uncommon item and is missable, though! I missed it myself. 

The fight in the basement is similarly missable. 

Great finds! Thanks for contributing!
